secret_token: <%= ENV['SECRET_TOKEN'] %>
twitter:
  key: <%= ENV['TWITTER_KEY'] %>
  secret: <%= ENV['TWITTER_SECRET'] %>
crypt:
  salt_length: <%= ENV['SALT_LENGTH'] %>
  stretching: <%= ENV['STRETCHING'] %>
  password: <%= ENV['PASSWORD']  %>
